export type TenXMission = {
  id: string;
  sourceId: string;
  rank: number;
  tier: string;
  category: string;
  title: string;
  detail: string;
  mechanism: string;
  successMetric: string;
  horizon: string;
  owner: string;
  leverage: number;
  tickets: number;
  status: 'ready';
};

const RAW_TEN_X_MISSIONS = [
  {
    "id": "10x-001",
    "sourceId": "10X-001",
    "rank": 1,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Limit the active portfolio to three outcomes",
    "detail": "Choose the three outcomes and mark every other project PARKED in the canonical registry.",
    "mechanism": "One Now lane, one Next lane, one protected incubator; everything else parked with an explicit restart trigger.",
    "successMetric": ">=80% of weekly work records map to the three active outcomes; no unplanned fourth lane.",
    "horizon": "Now",
    "owner": "Jay + Bob",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-002",
    "sourceId": "10X-002",
    "rank": 2,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Create one canonical project registry",
    "detail": "Import all 107 catalogued workstreams and mark canonical/merged/archived.",
    "mechanism": "One authoritative record for path, repo, branch, commit, owner, status, blocker, next action, proof, and confidence.",
    "successMetric": "100% of active work has one canonical path and no unresolved duplicate.",
    "horizon": "Now",
    "owner": "jcOS/JAY",
    "leverage": 96,
    "tickets": 4
  },
  {
    "id": "10x-003",
    "sourceId": "10X-003",
    "rank": 3,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Commit and tag the reviewed BOB baseline",
    "detail": "Review the live tree, preserve intentional files, commit, tag, and bind receipt.",
    "mechanism": "Exact-tree initial commit, tag, hash manifest, recovery receipt, and clean working state.",
    "successMetric": "BOB boots from a clean tagged commit and can be restored on a second machine.",
    "horizon": "Now",
    "owner": "Bob + Neo",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-004",
    "sourceId": "10X-004",
    "rank": 4,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Reconcile jcOS with released JAY 1.0.0",
    "detail": "Issue one reconciliation work order and update Bridge/current state from proof.",
    "mechanism": "Close or supersede stale work order; make the board reflect release evidence.",
    "successMetric": "No stale lifecycle state; jcOS and JAY agree on release commit and next action.",
    "horizon": "Now",
    "owner": "jcOS + Neo",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-005",
    "sourceId": "10X-005",
    "rank": 5,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Recover the canonical Rogue Maul source",
    "detail": "Search OneDrive/backups/GitHub and create a recovery manifest without mutating candidates.",
    "mechanism": "Locate, hash, back up, Git-baseline, and map source to published revision.",
    "successMetric": "Canonical repo, published revision, backup, and restore test all verified.",
    "horizon": "Now",
    "owner": "Bob + Trev + Neo",
    "leverage": 96,
    "tickets": 4
  },
  {
    "id": "10x-006",
    "sourceId": "10X-006",
    "rank": 6,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Release & QA",
    "title": "Create an owner acceptance matrix",
    "detail": "Run on the top 10 products.",
    "mechanism": "Install, launch, core flow, output, undo/rollback, restart, and accept/reject.",
    "successMetric": "Every active product has dated owner acceptance or explicit rejection.",
    "horizon": "Now",
    "owner": "Jay + Neo",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-007",
    "sourceId": "10X-007",
    "rank": 7,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Release & QA",
    "title": "Build one shared release factory",
    "detail": "Implement for Track Ripper, DJ Cleaner, and JTT.",
    "mechanism": "Reusable pipeline emits signed/versioned artifacts and evidence bundle.",
    "successMetric": "Three products release through the same pipeline with no manual packaging divergence.",
    "horizon": "30 days",
    "owner": "Trev + Neo",
    "leverage": 94,
    "tickets": 4
  },
  {
    "id": "10x-008",
    "sourceId": "10X-008",
    "rank": 8,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Portfolio",
    "title": "Automate the Rule of Three detector",
    "detail": "Instrument repeated launches, reports, handoffs, and file-finding actions.",
    "mechanism": "Track similar commands/tasks and create an improvement candidate after the third occurrence.",
    "successMetric": "At least five repeated workflows are automated or eliminated each month.",
    "horizon": "30 days",
    "owner": "JAY",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-009",
    "sourceId": "10X-009",
    "rank": 9,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Unify evidence and receipt contracts",
    "detail": "Define v1 receipt schema and migrate the next three releases.",
    "mechanism": "One schema for before/after, artifact hashes, tests, verifier, cost, duration, rollback, and acceptance.",
    "successMetric": "Every material action produces a machine-readable and human-readable receipt.",
    "horizon": "30 days",
    "owner": "JAY + jcOS",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-010",
    "sourceId": "10X-010",
    "rank": 10,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Release & QA",
    "title": "Canonicalize DJ Library Cleaner",
    "detail": "Freeze writes, compare both trees, declare canonical path.",
    "mechanism": "Select canonical tree, preserve best changes, baseline Git, fix table regression, run copied-library smoke.",
    "successMetric": "One clean repo, 228+ tests, user smoke, and release candidate.",
    "horizon": "Now",
    "owner": "Trev + Neo",
    "leverage": 96,
    "tickets": 4
  },
  {
    "id": "10x-011",
    "sourceId": "10X-011",
    "rank": 11,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Release & QA",
    "title": "Finish Track Ripper owner smoke and versioning",
    "detail": "Use the installed app on the failing URL and record output.",
    "mechanism": "Known-case acceptance plus Git baseline and release receipt.",
    "successMetric": "Download succeeds; metadata/filename correct; restart works; v1.0 tag exists.",
    "horizon": "Now",
    "owner": "Jay + Neo",
    "leverage": 93,
    "tickets": 4
  },
  {
    "id": "10x-012",
    "sourceId": "10X-012",
    "rank": 12,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Release & QA",
    "title": "Prove JTT with genuine LightBurn round-trip",
    "detail": "Select one portrait and one logo test case.",
    "mechanism": "Export from JTT, open in real LightBurn, inspect layers/settings, run safe material test, re-open saved file.",
    "successMetric": "Both files open cleanly and produce expected engraved output on the 100W machine.",
    "horizon": "Now",
    "owner": "Jay + Trev + Neo",
    "leverage": 96,
    "tickets": 4
  },
  {
    "id": "10x-013",
    "sourceId": "10X-013",
    "rank": 13,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Revenue",
    "title": "Complete the 10-unit birch production run",
    "detail": "Lock one original/licensed design and run the batch.",
    "mechanism": "Produce ten identical units while logging machine time, labor, defects, remakes, and material.",
    "successMetric": "10 sellable units, measured cost/time, and defect rate recorded.",
    "horizon": "Now",
    "owner": "Jay",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-014",
    "sourceId": "10X-014",
    "rank": 14,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Revenue",
    "title": "Calculate pocket-cash unit economics",
    "detail": "Fill the calculator from the 10-unit run.",
    "mechanism": "Price from cash after materials, fees, labor, defects, taxes reserve, and delivery.",
    "successMetric": "Every quote shows expected pocket cash and capacity impact.",
    "horizon": "Now",
    "owner": "Bob + Jay",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-015",
    "sourceId": "10X-015",
    "rank": 15,
    "tier": "Tier 1 - Immediate leverage",
    "category": "Control plane",
    "title": "Install automatic monthly work snapshots",
    "detail": "Schedule the first snapshot for August 31 and test restore/readability.",
    "mechanism": "Monthly immutable export of project state, task ledger, Git evidence, artifacts, and decisions.",
    "successMetric": "No future month lacks a complete review package.",
    "horizon": "Now",
    "owner": "JAY",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-016",
    "sourceId": "10X-016",
    "rank": 16,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Create a weekly stop-doing review",
    "detail": "Run the first review against the 107-workstream register.",
    "mechanism": "Review work with no owner, proof, customer, or strategic role.",
    "successMetric": "At least 20 lanes are merged, archived, or explicitly parked.",
    "horizon": "Now",
    "owner": "Jay + Bob",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-017",
    "sourceId": "10X-017",
    "rank": 17,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Measure outcome throughput instead of task volume",
    "detail": "Add six outcome KPIs to the dashboard.",
    "mechanism": "Track accepted outcomes, cycle time, rework, owner interruptions, and pocket cash.",
    "successMetric": "Monthly review leads with accepted outcomes, not task count.",
    "horizon": "Now",
    "owner": "Bob",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-018",
    "sourceId": "10X-018",
    "rank": 18,
    "tier": "Tier 2 - Next 30 days",
    "category": "Release & QA",
    "title": "Require clean-tree or documented-dirty release state",
    "detail": "Apply to CashAvalance, BOB, DJ Cleaner, BoardBrain, BuildStuffRed, System Monitor, Render Bender.",
    "mechanism": "Release gate fails unless changes are committed, intentionally ignored, or listed in manifest.",
    "successMetric": "No artifact ships from an unexplained dirty tree.",
    "horizon": "Now",
    "owner": "Neo",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-019",
    "sourceId": "10X-019",
    "rank": 19,
    "tier": "Tier 2 - Next 30 days",
    "category": "Release & QA",
    "title": "Separate feature-complete from product-accepted",
    "detail": "Update status model and current top 10 projects.",
    "mechanism": "Two independent gates: engineering complete and owner/customer accepted.",
    "successMetric": "No project displays RELEASED without owner/customer acceptance.",
    "horizon": "Now",
    "owner": "jcOS",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-020",
    "sourceId": "10X-020",
    "rank": 20,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Standardize project stage labels",
    "detail": "Relabel all 107 workstreams.",
    "mechanism": "One stage model with evidence required for each transition.",
    "successMetric": "No project is called complete without its required evidence.",
    "horizon": "Now",
    "owner": "jcOS",
    "leverage": 98,
    "tickets": 4
  },
  {
    "id": "10x-021",
    "sourceId": "10X-021",
    "rank": 21,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Use a decision budget for major new ideas",
    "detail": "Set a two-new-idea monthly budget.",
    "mechanism": "Allow a fixed monthly number of new incubator entries; extras go to an idea vault.",
    "successMetric": "No active-lane displacement from unscheduled ideation.",
    "horizon": "Now",
    "owner": "Jay + Bob",
    "leverage": 95,
    "tickets": 4
  },
  {
    "id": "10x-022",
    "sourceId": "10X-022",
    "rank": 22,
    "tier": "Tier 2 - Next 30 days",
    "category": "Control plane",
    "title": "Create a project lineage map",
    "detail": "Publish one diagram and migration table.",
    "mechanism": "Graph predecessor, successor, absorbed capabilities, authority, and archive state.",
    "successMetric": "Every operating-layer component has one role and no competing authority.",
    "horizon": "30 days",
    "owner": "Bob + jcOS",
    "leverage": 94,
    "tickets": 4
  },
  {
    "id": "10x-023",
    "sourceId": "10X-023",
    "rank": 23,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Reduce handoff count per outcome",
    "detail": "Measure handoffs on the next three work orders.",
    "mechanism": "Default one accountable executor plus one verifier; spawn specialists only for distinct evidence.",
    "successMetric": "Median handoffs per accepted outcome falls by at least 50%.",
    "horizon": "30 days",
    "owner": "Bob",
    "leverage": 94,
    "tickets": 4
  },
  {
    "id": "10x-024",
    "sourceId": "10X-024",
    "rank": 24,
    "tier": "Tier 2 - Next 30 days",
    "category": "Release & QA",
    "title": "Run Rogue Maul physical-device acceptance",
    "detail": "Test on iPhone 14 and Galaxy S9 with video receipts.",
    "mechanism": "Scripted Safari/Chrome tests for launch, rotation, HUD, touch, persistence, offline restart, and performance.",
    "successMetric": "All mandatory scenarios pass on both devices.",
    "horizon": "Now",
    "owner": "Jay + Neo",
    "leverage": 93,
    "tickets": 4
  },
  {
    "id": "10x-025",
    "sourceId": "10X-025",
    "rank": 25,
    "tier": "Tier 2 - Next 30 days",
    "category": "Revenue",
    "title": "Use original/licensed art by default",
    "detail": "Create three original collectible-card templates.",
    "mechanism": "Original universe, customer-authorized assets, or licensed content.",
    "successMetric": "100% of commercial samples have documented rights status.",
    "horizon": "Now",
    "owner": "Muse + Jay",
    "leverage": 93,
    "tickets": 4
  },
  {
    "id": "10x-026",
    "sourceId": "10X-026",
    "rank": 26,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Create a duplicate-capability check before new projects",
    "detail": "Add a doctrine gate to the app master-prompt workflow.",
    "mechanism": "New-project intake searches the ecosystem spine and recommends reuse/extend/integrate.",
    "successMetric": "Every new project documents reused services before code begins.",
    "horizon": "30 days",
    "owner": "Trev",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-027",
    "sourceId": "10X-027",
    "rank": 27,
    "tier": "Tier 2 - Next 30 days",
    "category": "Revenue",
    "title": "Create a production-capacity dashboard",
    "detail": "Instrument the 10-unit run and next three jobs.",
    "mechanism": "Machine minutes, setup, labor, queue, defects, maintenance, and weekly limit.",
    "successMetric": "Quotes automatically respect verified weekly capacity.",
    "horizon": "60 days",
    "owner": "JAY + Jay",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-028",
    "sourceId": "10X-028",
    "rank": 28,
    "tier": "Tier 2 - Next 30 days",
    "category": "Knowledge & team",
    "title": "Create an operating review cadence",
    "detail": "Schedule and template all four cadences in JAY.",
    "mechanism": "Daily brief, weekly outcome review, monthly evidence snapshot, quarterly 10x review.",
    "successMetric": "Reviews happen automatically and each produces a decision/action artifact.",
    "horizon": "30 days",
    "owner": "Bob/JAY",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-029",
    "sourceId": "10X-029",
    "rank": 29,
    "tier": "Tier 2 - Next 30 days",
    "category": "Shared platform",
    "title": "Create universal work-order templates",
    "detail": "Create templates for software, fabrication, repair, creative, and research.",
    "mechanism": "Outcome, scope, constraints, authority, inputs, acceptance, evidence, rollback.",
    "successMetric": "90% of substantive work starts from a typed work order.",
    "horizon": "30 days",
    "owner": "Bob",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-030",
    "sourceId": "10X-030",
    "rank": 30,
    "tier": "Tier 2 - Next 30 days",
    "category": "Control plane",
    "title": "Enforce one live writer per checkout",
    "detail": "Add a checkout lock/lease check to every build Skill.",
    "mechanism": "Durable writer lease with task ID, expiry, heartbeat, and safe takeover.",
    "successMetric": "Zero overlapping writers and zero merge/recovery incidents for 30 days.",
    "horizon": "Now",
    "owner": "JAY",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-031",
    "sourceId": "10X-031",
    "rank": 31,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Make every project resume from one card",
    "detail": "Implement for Rogue Maul, JTT, and DJ Cleaner.",
    "mechanism": "Resume card loads canonical repo, current proof, blocker, next task, and work order.",
    "successMetric": "A cold restart reaches productive work in under two minutes.",
    "horizon": "30 days",
    "owner": "JAY",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-032",
    "sourceId": "10X-032",
    "rank": 32,
    "tier": "Tier 2 - Next 30 days",
    "category": "Control plane",
    "title": "Make project status evidence-derived",
    "detail": "Replace manual status on the top 10 projects with calculated state projections.",
    "mechanism": "Derive status from Git, artifacts, receipts, tests, owner acceptance, and timestamps.",
    "successMetric": "No status older than 7 days without an explicit STALE flag.",
    "horizon": "30 days",
    "owner": "jcOS",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-033",
    "sourceId": "10X-033",
    "rank": 33,
    "tier": "Tier 2 - Next 30 days",
    "category": "Knowledge & team",
    "title": "Measure founder-time allocation",
    "detail": "Run a two-week time audit automatically through JAY.",
    "mechanism": "Track visionary, production, admin, coordination, repair, and wasted/rework time.",
    "successMetric": "Founder coordination/admin time falls by 30% quarter over quarter.",
    "horizon": "30 days",
    "owner": "JAY",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-034",
    "sourceId": "10X-034",
    "rank": 34,
    "tier": "Tier 2 - Next 30 days",
    "category": "Revenue",
    "title": "Secure one paid B2B pilot",
    "detail": "Build a 20-prospect list and contact five qualified buyers.",
    "mechanism": "Target one Long Beach/Downey purchasing authority with samples and reorder use case.",
    "successMetric": "One profitable paid pilot completed.",
    "horizon": "30 days",
    "owner": "Jay + Bob",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-035",
    "sourceId": "10X-035",
    "rank": 35,
    "tier": "Tier 2 - Next 30 days",
    "category": "Control plane",
    "title": "Separate executor from verifier everywhere",
    "detail": "Require verifier_id on every COMPLETE transition.",
    "mechanism": "Neo or deterministic gates independently verify before state commit.",
    "successMetric": "100% of active-project completions have independent verification.",
    "horizon": "30 days",
    "owner": "JAY/Neo",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-036",
    "sourceId": "10X-036",
    "rank": 36,
    "tier": "Tier 2 - Next 30 days",
    "category": "Revenue",
    "title": "Track cash entering Jay's pocket",
    "detail": "Add the metric to JAY Today dashboard.",
    "mechanism": "Daily/weekly pocket-cash ledger linked to project and hours.",
    "successMetric": "Every paid job/product shows pocket cash and effective hourly return.",
    "horizon": "30 days",
    "owner": "JAY",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-037",
    "sourceId": "10X-037",
    "rank": 37,
    "tier": "Tier 2 - Next 30 days",
    "category": "Control plane",
    "title": "Turn JAY's phase plan into gated work orders",
    "detail": "Create Phase 0-4 gate records in jcOS.",
    "mechanism": "Each phase has exact entry criteria, work orders, acceptance, and blocking policy.",
    "successMetric": "No phase advances without its gate; no new critical-path scope without replacement.",
    "horizon": "30 days",
    "owner": "JAY + jcOS",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-038",
    "sourceId": "10X-038",
    "rank": 38,
    "tier": "Tier 2 - Next 30 days",
    "category": "Portfolio",
    "title": "Use one work order per owner-valued outcome",
    "detail": "Reframe DJ Cleaner acceptance as one work order.",
    "mechanism": "One parent work order owns all child tasks, evidence, and acceptance.",
    "successMetric": "Task-count inflation drops; status is readable from one record.",
    "horizon": "30 days",
    "owner": "jcOS",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-039",
    "sourceId": "10X-039",
    "rank": 39,
    "tier": "Tier 2 - Next 30 days",
    "category": "Product-specific",
    "title": "Version Rogue Maul content waves",
    "detail": "Publish an acceptance matrix per wave.",
    "mechanism": "Wave 1 release foundation, Wave 2 towers/UI, Wave 3 relic modal/progression.",
    "successMetric": "No wave is called complete with open mandatory gates.",
    "horizon": "30 days",
    "owner": "Rogue Maul",
    "leverage": 92,
    "tickets": 4
  },
  {
    "id": "10x-040",
    "sourceId": "10X-040",
    "rank": 40,
    "tier": "Tier 2 - Next 30 days",
    "category": "Revenue",
    "title": "Create a no-favor/no-exposure quote rule",
    "detail": "Add classification to quote/work-order intake.",
    "mechanism": "Every request gets cash, strategic exchange, or explicit personal-gift classification.",
    "successMetric": "No unclassified external work enters the queue.",
    "horizon": "Now",
    "owner": "Bob",
    "leverage": 91,
    "tickets": 4
  },
  {
    "id": "10x-041",
    "sourceId": "10X-041",
    "rank": 41,
    "tier": "Tier 3 - Next 60 days",
    "category": "Knowledge & team",
    "title": "Auto-turn durable conversation outcomes into artifacts",
    "detail": "Enable for the next 20 substantive conversations.",
    "mechanism": "Classifier drafts doctrine/spec/work order/decision/lesson artifacts and asks only when ambiguous.",
    "successMetric": ">=90% of durable outcomes are preserved within the same session.",
    "horizon": "30 days",
    "owner": "Bob/JAY",
    "leverage": 90,
    "tickets": 4
  },
  {
    "id": "10x-042",
    "sourceId": "10X-042",
    "rank": 42,
    "tier": "Tier 3 - Next 60 days",
    "category": "Portfolio",
    "title": "Create an owner-attention queue",
    "detail": "Classify all open items Green/Yellow/Red.",
    "mechanism": "Only true decisions, failures, money, external commitments, and irreversible changes surface.",
    "successMetric": "Routine Green work causes zero owner interruptions.",
    "horizon": "60 days",
    "owner": "Bob/JAY",
    "leverage": 90,
    "tickets": 4
  },
  {
    "id": "10x-043",
    "sourceId": "10X-043",
    "rank": 43,
    "tier": "Tier 3 - Next 60 days",
    "category": "Shared platform",
    "title": "Create one archive and durable-memory service",
    "detail": "Auto-save the next five decisions/specs/work orders.",
    "mechanism": "Automatic artifact capture, indexing, links, checksums, and retention.",
    "successMetric": "Bob retrieves any durable decision in under 10 seconds.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 90,
    "tickets": 4
  },
  {
    "id": "10x-044",
    "sourceId": "10X-044",
    "rank": 44,
    "tier": "Tier 3 - Next 60 days",
    "category": "Shared platform",
    "title": "Create one installer/update/diagnostics SDK",
    "detail": "Extract from Track Ripper and JAY release work.",
    "mechanism": "Shared installer, portable build, update channel, logs, diagnostics, and rollback.",
    "successMetric": "New desktop app gets production packaging in under one day.",
    "horizon": "60 days",
    "owner": "Trev",
    "leverage": 90,
    "tickets": 4
  },
  {
    "id": "10x-045",
    "sourceId": "10X-045",
    "rank": 45,
    "tier": "Tier 3 - Next 60 days",
    "category": "Shared platform",
    "title": "Create reusable preview-before-write service",
    "detail": "Extract from CTRL ALT DJC and JAY.",
    "mechanism": "Common change plan, diff, approval, execution, verification, and undo.",
    "successMetric": "Three products use the same mutation contract.",
    "horizon": "60 days",
    "owner": "Trev",
    "leverage": 90,
    "tickets": 4
  },
  {
    "id": "10x-046",
    "sourceId": "10X-046",
    "rank": 46,
    "tier": "Tier 3 - Next 60 days",
    "category": "Home operations",
    "title": "Capture measurements once at the source",
    "detail": "Measure all exterior segments and unfinished rooms.",
    "mechanism": "Phone-guided measurement checklist with photo annotations and confidence.",
    "successMetric": "V2 plan has no provisional geometry for measured areas.",
    "horizon": "30 days",
    "owner": "Jay",
    "leverage": 89,
    "tickets": 4
  },
  {
    "id": "10x-047",
    "sourceId": "10X-047",
    "rank": 47,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Create a canonical decisions ledger",
    "detail": "Import 25 load-bearing decisions from doctrine, PRD, and recent work.",
    "mechanism": "Dated decision records with rationale, scope, affected projects, and supersession.",
    "successMetric": "Bob answers \"what did Jay decide?\" from one ledger.",
    "horizon": "30 days",
    "owner": "Bob/jcOS",
    "leverage": 89,
    "tickets": 4
  },
  {
    "id": "10x-048",
    "sourceId": "10X-048",
    "rank": 48,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Create a safe archive/supersession workflow",
    "detail": "Archive one predecessor (e.g., Neat Nastiness or Trev OS component) end to end.",
    "mechanism": "Read-only archive, superseded banner, successor link, restore instructions.",
    "successMetric": "Archived systems cannot be mistaken for current authority.",
    "horizon": "30 days",
    "owner": "jcOS",
    "leverage": 89,
    "tickets": 4
  },
  {
    "id": "10x-049",
    "sourceId": "10X-049",
    "rank": 49,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Install stale-state alarms",
    "detail": "Add rules for release-after-work-order and status older than evidence.",
    "mechanism": "Time and evidence-aware alerts for conflicting or old state.",
    "successMetric": "All contradictions are flagged within one refresh cycle.",
    "horizon": "30 days",
    "owner": "jcOS",
    "leverage": 89,
    "tickets": 4
  },
  {
    "id": "10x-050",
    "sourceId": "10X-050",
    "rank": 50,
    "tier": "Tier 3 - Next 60 days",
    "category": "Revenue",
    "title": "Launch preorder-first physical products",
    "detail": "Use on the Labor Day photo engraving offer.",
    "mechanism": "Paid preorder or deposit before production batch.",
    "successMetric": "Five paid orders before batch production.",
    "horizon": "30 days",
    "owner": "Jay",
    "leverage": 89,
    "tickets": 4
  },
  {
    "id": "10x-051",
    "sourceId": "10X-051",
    "rank": 51,
    "tier": "Tier 3 - Next 60 days",
    "category": "Portfolio",
    "title": "Require restart triggers for parked ideas",
    "detail": "Add trigger and next-review date to all parked projects.",
    "mechanism": "Each parked item gets a trigger such as paid demand, prerequisite complete, or scheduled review.",
    "successMetric": "No parked project restarts without its trigger.",
    "horizon": "30 days",
    "owner": "jcOS",
    "leverage": 89,
    "tickets": 4
  },
  {
    "id": "10x-052",
    "sourceId": "10X-052",
    "rank": 52,
    "tier": "Tier 3 - Next 60 days",
    "category": "Revenue",
    "title": "Engineer the first reorder",
    "detail": "Include a dated reorder offer in the first B2B pilot.",
    "mechanism": "Design product/use case around replenishment, employee recognition, events, or recurring promotions.",
    "successMetric": "A credible repeat order or standing schedule is secured.",
    "horizon": "60 days",
    "owner": "Jay + Bob",
    "leverage": 88,
    "tickets": 4
  },
  {
    "id": "10x-053",
    "sourceId": "10X-053",
    "rank": 53,
    "tier": "Tier 3 - Next 60 days",
    "category": "Portfolio",
    "title": "Add confidence and freshness to every status",
    "detail": "Apply to the active portfolio and top 20 parked lanes.",
    "mechanism": "Status stores confidence, source count, last verification, and stale threshold.",
    "successMetric": "Bob's briefing distinguishes fact, inference, and unknown automatically.",
    "horizon": "30 days",
    "owner": "jcOS",
    "leverage": 87,
    "tickets": 4
  },
  {
    "id": "10x-054",
    "sourceId": "10X-054",
    "rank": 54,
    "tier": "Tier 3 - Next 60 days",
    "category": "Revenue",
    "title": "Create a local B2B sample kit",
    "detail": "Build one 6-piece kit from existing laser capabilities.",
    "mechanism": "Compact sample set, price ranges, turnaround, personalization options, and QR portfolio.",
    "successMetric": "At least 10 qualified meetings use the same kit.",
    "horizon": "30 days",
    "owner": "Jay",
    "leverage": 87,
    "tickets": 4
  },
  {
    "id": "10x-055",
    "sourceId": "10X-055",
    "rank": 55,
    "tier": "Tier 3 - Next 60 days",
    "category": "Portfolio",
    "title": "Create a reusable app specification factory",
    "detail": "Convert the standing \"I want to make an app\" rule into a generator.",
    "mechanism": "Parameterized master spec composes shared standards and project-specific modules.",
    "successMetric": "A complete bounded spec is produced in under five minutes with no omitted gates.",
    "horizon": "30 days",
    "owner": "Trev",
    "leverage": 87,
    "tickets": 4
  },
  {
    "id": "10x-056",
    "sourceId": "10X-056",
    "rank": 56,
    "tier": "Tier 3 - Next 60 days",
    "category": "Shared platform",
    "title": "Create shared confidence/proof scoring",
    "detail": "Apply to project status and house observations.",
    "mechanism": "Score source quality, recency, independent verification, and owner acceptance.",
    "successMetric": "Every important claim displays evidence grade and confidence.",
    "horizon": "60 days",
    "owner": "jcOS",
    "leverage": 87,
    "tickets": 4
  },
  {
    "id": "10x-057",
    "sourceId": "10X-057",
    "rank": 57,
    "tier": "Tier 3 - Next 60 days",
    "category": "Release & QA",
    "title": "Use canary releases on the spare PC",
    "detail": "Canary the next JAY and Track Ripper release.",
    "mechanism": "Install and smoke on spare PC before promotion to main.",
    "successMetric": "No main-PC promotion without passing canary receipt.",
    "horizon": "30 days",
    "owner": "Neo",
    "leverage": 87,
    "tickets": 4
  },
  {
    "id": "10x-058",
    "sourceId": "10X-058",
    "rank": 58,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Add second-machine restore proof",
    "detail": "Restore JAY/BOB onto the spare PC from current backups.",
    "mechanism": "Automated clean-machine install, restore, pair, smoke, and receipt.",
    "successMetric": "Recovery objective met with no development tools and no lost state.",
    "horizon": "60 days",
    "owner": "JAY + Neo",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-059",
    "sourceId": "10X-059",
    "rank": 59,
    "tier": "Tier 3 - Next 60 days",
    "category": "Release & QA",
    "title": "Automate reboot/recovery tests",
    "detail": "Add to JAY and one product release pipeline.",
    "mechanism": "Kill process, reboot, reconnect, resume/rollback, verify no duplicate side effect.",
    "successMetric": "100% of tested jobs recover deterministically.",
    "horizon": "60 days",
    "owner": "Neo",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-060",
    "sourceId": "10X-060",
    "rank": 60,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Bind approvals to exact plan hashes",
    "detail": "Use hash-bound approval on the next Yellow/Red action.",
    "mechanism": "Approval scope includes skill, target, plan hash, amount, and expiry.",
    "successMetric": "Changed plan automatically invalidates prior approval.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-061",
    "sourceId": "10X-061",
    "rank": 61,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Create a global kill switch and budget ceiling",
    "detail": "Implement and test kill switch during an active test job.",
    "mechanism": "Per-job, daily, weekly budgets; provider retry caps; global pause.",
    "successMetric": "New claims stop safely; active work drains/rolls back; receipt produced.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-062",
    "sourceId": "10X-062",
    "rank": 62,
    "tier": "Tier 3 - Next 60 days",
    "category": "Shared platform",
    "title": "Create a machine and equipment asset registry",
    "detail": "Register the 100W laser, Ender 3, main PC, MacBook, XDJ-XZ, APC40, and mini-split.",
    "mechanism": "Asset ID, model, location, manuals, maintenance, issues, parts, photos, and receipts.",
    "successMetric": "Future diagnosis begins from asset history, not repeated questions.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-063",
    "sourceId": "10X-063",
    "rank": 63,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Implement deterministic-first intent routing",
    "detail": "Instrument the top 20 commands and replace avoidable model calls.",
    "mechanism": "Intelligence ladder: cache → code → local analysis → small model → large model.",
    "successMetric": ">=70% of routine commands complete without a model call.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-064",
    "sourceId": "10X-064",
    "rank": 64,
    "tier": "Tier 3 - Next 60 days",
    "category": "Control plane",
    "title": "Make the UI a projection, never a truth store",
    "detail": "Audit JAY, jcOS, BOB, BoardBrain, Drive Brain for local state duplication.",
    "mechanism": "All interfaces read/write through canonical service and event ledger.",
    "successMetric": "No user-facing surface owns competing project state.",
    "horizon": "60 days",
    "owner": "Trev + Neo",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-065",
    "sourceId": "10X-065",
    "rank": 65,
    "tier": "Tier 3 - Next 60 days",
    "category": "Product-specific",
    "title": "Merge the photo-product family",
    "detail": "Declare one canonical repo and migration plan.",
    "mechanism": "One local photo platform with cleanup, search, people, OCR, video, and safe-delete modules.",
    "successMetric": "One product name/repo serves both cleanup and memory search.",
    "horizon": "60 days",
    "owner": "JayProducts",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-066",
    "sourceId": "10X-066",
    "rank": 66,
    "tier": "Tier 3 - Next 60 days",
    "category": "Product-specific",
    "title": "Turn JTT tests into a proprietary material intelligence moat",
    "detail": "Log 20 standardized tests.",
    "mechanism": "Capture image type, material lot, focus, speed/power, air assist, result photo, and rating.",
    "successMetric": "Presets predict acceptable first-pass results with measured confidence.",
    "horizon": "90 days",
    "owner": "Jay + JTT",
    "leverage": 86,
    "tickets": 4
  },
  {
    "id": "10x-067",
    "sourceId": "10X-067",
    "rank": 67,
    "tier": "Tier 3 - Next 60 days",
    "category": "Portfolio",
    "title": "Run quarterly keep/kill/merge reviews",
    "detail": "Score every project with Grade C/D evidence.",
    "mechanism": "Score strategic fit, proof, demand, uniqueness, maintenance, and joy.",
    "successMetric": "At least 25% of low-confidence lanes are merged/archived per quarter.",
    "horizon": "90 days",
    "owner": "Jay + Bob",
    "leverage": 85,
    "tickets": 4
  },
  {
    "id": "10x-068",
    "sourceId": "10X-068",
    "rank": 68,
    "tier": "Tier 3 - Next 60 days",
    "category": "Home operations",
    "title": "Build the room/object/task Digital Twin",
    "detail": "Create the schema and import the five rendered rooms.",
    "mechanism": "Room → object → issue/task → evidence → owner → status → recurrence.",
    "successMetric": "Any house task is found by room/photo and updated with proof.",
    "horizon": "90 days",
    "owner": "JAY Home",
    "leverage": 84,
    "tickets": 4
  },
  {
    "id": "10x-069",
    "sourceId": "10X-069",
    "rank": 69,
    "tier": "Tier 3 - Next 60 days",
    "category": "Product-specific",
    "title": "Make PushMyButtons self-configuring",
    "detail": "Build setup doctor using known failure logs.",
    "mechanism": "Device detection, signal test, loopback recommendation, controller map, and recovery wizard.",
    "successMetric": "A clean PC reaches working visuals in under 10 minutes.",
    "horizon": "90 days",
    "owner": "DJ tools",
    "leverage": 84,
    "tickets": 4
  },
  {
    "id": "10x-070",
    "sourceId": "10X-070",
    "rank": 70,
    "tier": "Tier 3 - Next 60 days",
    "category": "Home operations",
    "title": "Attach costs and warranties to property assets",
    "detail": "Import dishwasher and blinds records.",
    "mechanism": "Asset record includes purchase, installer, labor, warranty, photos, and next maintenance.",
    "successMetric": "Future repair/tenant questions use the asset ledger immediately.",
    "horizon": "60 days",
    "owner": "JAY Home",
    "leverage": 83,
    "tickets": 4
  },
  {
    "id": "10x-071",
    "sourceId": "10X-071",
    "rank": 71,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Product-specific",
    "title": "Fold Jay System Monitor into JAY",
    "detail": "Inventory existing code and create migration work order.",
    "mechanism": "System Monitor becomes a JAY Skill/widget using shared alerts and receipts.",
    "successMetric": "One machine-health source replaces two apps.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 83,
    "tickets": 4
  },
  {
    "id": "10x-072",
    "sourceId": "10X-072",
    "rank": 72,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Product-specific",
    "title": "Turn Track Ripper's browser handoff into a frictionless flow",
    "detail": "Prove current Ctrl+Alt+C flow before considering extension.",
    "mechanism": "Clipboard hotkey, browser helper, queue, retry, source diagnostics, and duplicate detection.",
    "successMetric": "A first-time user completes download without opening a terminal or settings.",
    "horizon": "60 days",
    "owner": "DJ tools",
    "leverage": 83,
    "tickets": 4
  },
  {
    "id": "10x-073",
    "sourceId": "10X-073",
    "rank": 73,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Revenue",
    "title": "Turn quotes into reusable packages",
    "detail": "Rebuild the wedding tiers in a quote generator.",
    "mechanism": "Parameterized package templates tied to inventory, cost, schedule, and margin.",
    "successMetric": "A new quote is produced accurately in under five minutes.",
    "horizon": "60 days",
    "owner": "Bob",
    "leverage": 83,
    "tickets": 4
  },
  {
    "id": "10x-074",
    "sourceId": "10X-074",
    "rank": 74,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Release & QA",
    "title": "Create two-hour live burn-ins for performance tools",
    "detail": "Run one controlled live-set simulation.",
    "mechanism": "Automated logging plus real audio/MIDI/projectM workload for two hours.",
    "successMetric": "No crash, audio silence, stuck preset, or unrecoverable controller loss.",
    "horizon": "30 days",
    "owner": "Jay + Neo",
    "leverage": 82,
    "tickets": 4
  },
  {
    "id": "10x-075",
    "sourceId": "10X-075",
    "rank": 75,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Centralize settings/configuration",
    "detail": "Pilot with Track Ripper, DJ Cleaner, and JTT.",
    "mechanism": "Shared versioned settings service with app namespaces and migration.",
    "successMetric": "Three apps use one settings service without breaking standalone operation.",
    "horizon": "90 days",
    "owner": "JAY/Trev",
    "leverage": 82,
    "tickets": 4
  },
  {
    "id": "10x-076",
    "sourceId": "10X-076",
    "rank": 76,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Release & QA",
    "title": "Create a universal rollback button",
    "detail": "Implement for JAY release factory.",
    "mechanism": "Product-level restore point, previous artifact, data backup, and one-click rollback.",
    "successMetric": "Rollback completes and verifies in under five minutes.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 82,
    "tickets": 4
  },
  {
    "id": "10x-077",
    "sourceId": "10X-077",
    "rank": 77,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Revenue",
    "title": "Use paid design partners before public SaaS",
    "detail": "Recruit one design partner for JTT.",
    "mechanism": "Three high-fit users get guided setup in exchange for payment and feedback.",
    "successMetric": "Three paid users complete the core workflow and request continuation.",
    "horizon": "90 days",
    "owner": "Jay + Bob",
    "leverage": 82,
    "tickets": 4
  },
  {
    "id": "10x-078",
    "sourceId": "10X-078",
    "rank": 78,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Release & QA",
    "title": "Add release health telemetry without surveillance",
    "detail": "Add to shared release factory.",
    "mechanism": "Local logs, crash bundle, environment snapshot, and one-click diagnostics export.",
    "successMetric": "A user can generate a complete redacted support bundle in one click.",
    "horizon": "60 days",
    "owner": "Trev",
    "leverage": 81,
    "tickets": 4
  },
  {
    "id": "10x-079",
    "sourceId": "10X-079",
    "rank": 79,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Release & QA",
    "title": "Add visual regression snapshots",
    "detail": "Add to DJ Cleaner, JAY, and house render pipeline.",
    "mechanism": "Golden screenshots at key viewport sizes with human review thresholds.",
    "successMetric": "Known visual regressions are caught before owner testing.",
    "horizon": "60 days",
    "owner": "Neo",
    "leverage": 81,
    "tickets": 4
  },
  {
    "id": "10x-080",
    "sourceId": "10X-080",
    "rank": 80,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create a reusable diagnostics bundle",
    "detail": "Package the Mac pre-boot and JAY diagnostics into a shared tool.",
    "mechanism": "One-click redacted logs, versions, processes, storage, network, crash, and app config.",
    "successMetric": "Support starts with a complete bundle in under two minutes.",
    "horizon": "60 days",
    "owner": "JAY",
    "leverage": 81,
    "tickets": 4
  },
  {
    "id": "10x-081",
    "sourceId": "10X-081",
    "rank": 81,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Release & QA",
    "title": "Create reusable benchmark fixtures",
    "detail": "Create fixtures for That One Photo, DJ Cleaner, JTT, and ToonCapture.",
    "mechanism": "Small versioned datasets and expected outcomes for retrieval, metadata, images, audio, and builds.",
    "successMetric": "Quality changes are measured against stable benchmarks.",
    "horizon": "60 days",
    "owner": "Trev + Neo",
    "leverage": 81,
    "tickets": 4
  },
  {
    "id": "10x-082",
    "sourceId": "10X-082",
    "rank": 82,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Product-specific",
    "title": "Convert CashAvalance into a dark-pattern detector",
    "detail": "Write a safe anti-pattern specification from the prototype.",
    "mechanism": "Catalog mechanics, user harms, legal flags, and prohibited implementation patterns.",
    "successMetric": "Future products automatically flag prohibited mechanics.",
    "horizon": "60 days",
    "owner": "JayProducts",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-083",
    "sourceId": "10X-083",
    "rank": 83,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Home operations",
    "title": "Create recurring home reset routines",
    "detail": "Implement front-door → studio weekly reset.",
    "mechanism": "Room checklists, minimum reset state, recurrence, supplies, and photo proof.",
    "successMetric": "Weekly reset completes with fewer than five owner decisions.",
    "horizon": "30 days",
    "owner": "JAY Home",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-084",
    "sourceId": "10X-084",
    "rank": 84,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create local search across all artifacts",
    "detail": "Index the current review package and top 10 repos.",
    "mechanism": "Index metadata and extracted text locally; retrieve narrow relevant context.",
    "successMetric": "Bob answers source-backed project questions without broad context dumps.",
    "horizon": "90 days",
    "owner": "JAY/Drive Brain",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-085",
    "sourceId": "10X-085",
    "rank": 85,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create one AI/model gateway",
    "detail": "Route one active product and Bob through the gateway.",
    "mechanism": "Central route by task, cost, privacy, context size, and failure state.",
    "successMetric": "Provider failure pauses safely; usage/cost is visible per job.",
    "horizon": "90 days",
    "owner": "JAY",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-086",
    "sourceId": "10X-086",
    "rank": 86,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create one media-ingestion pipeline",
    "detail": "Pilot with DJ files and house photos.",
    "mechanism": "Hash, metadata, duplicate detection, preview, safe copy, provenance, and archive.",
    "successMetric": "The same asset is never duplicated or lost across two pipelines.",
    "horizon": "90 days",
    "owner": "Trev",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-087",
    "sourceId": "10X-087",
    "rank": 87,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create one permissions and safety engine",
    "detail": "Apply to ShutUpSlut, JAY, and file cleanup.",
    "mechanism": "Shared Green/Yellow/Red policy and capability manifests.",
    "successMetric": "No product can bypass the same core risk policy.",
    "horizon": "90 days",
    "owner": "JAY",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-088",
    "sourceId": "10X-088",
    "rank": 88,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create phone supervision as a thin surface",
    "detail": "Implement read-only PWA for active JAY jobs.",
    "mechanism": "Today, approvals, cancel/hold, progress, receipts, and alerts only.",
    "successMetric": "Jay can supervise from phone without bypassing policy or opening the PC.",
    "horizon": "90 days",
    "owner": "JAY",
    "leverage": 80,
    "tickets": 4
  },
  {
    "id": "10x-089",
    "sourceId": "10X-089",
    "rank": 89,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Revenue",
    "title": "Create a repair-assistant lead magnet",
    "detail": "Prototype as a form/report before an app.",
    "mechanism": "Photo upload → issue summary → tool/parts checklist → safe next step → local service option.",
    "successMetric": "Ten real submissions and measured usefulness.",
    "horizon": "60 days",
    "owner": "JayProducts",
    "leverage": 79,
    "tickets": 4
  },
  {
    "id": "10x-090",
    "sourceId": "10X-090",
    "rank": 90,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Knowledge & team",
    "title": "Define the first-hire trigger from actual bottlenecks",
    "detail": "Use time audit and production run to score candidate roles.",
    "mechanism": "Role appears only after documented recurring demand, stable revenue, and measurable output.",
    "successMetric": "First hire removes the largest teachable recurring burden and is revenue-supported.",
    "horizon": "90 days",
    "owner": "Jay + Bob",
    "leverage": 79,
    "tickets": 4
  },
  {
    "id": "10x-091",
    "sourceId": "10X-091",
    "rank": 91,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Revenue",
    "title": "Price software by saved pain, not feature count",
    "detail": "Benchmark Track Ripper, JTT, and DJ Cleaner.",
    "mechanism": "Measure time, errors, risk, and avoided labor in user tests.",
    "successMetric": "Each active software product has a quantified value proposition.",
    "horizon": "60 days",
    "owner": "Bob + Jay",
    "leverage": 79,
    "tickets": 4
  },
  {
    "id": "10x-092",
    "sourceId": "10X-092",
    "rank": 92,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Knowledge & team",
    "title": "Create a content-from-proof pipeline",
    "detail": "Produce one Made in the Garage video from the 10-unit run.",
    "mechanism": "Receipts, build clips, before/after images, metrics, and lessons generate draft content automatically.",
    "successMetric": "One work session yields a finished long-form draft plus three shorts.",
    "horizon": "60 days",
    "owner": "Muse",
    "leverage": 77,
    "tickets": 4
  },
  {
    "id": "10x-093",
    "sourceId": "10X-093",
    "rank": 93,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Home operations",
    "title": "Create equipment diagnostic trees",
    "detail": "Build the mini-split and Ender 3 flows first.",
    "mechanism": "Asset-specific guided tests that collect model, symptoms, readings, and safe stop conditions.",
    "successMetric": "Future diagnosis starts with complete evidence and avoids repeated questions.",
    "horizon": "60 days",
    "owner": "AI Repair Assistant",
    "leverage": 77,
    "tickets": 4
  },
  {
    "id": "10x-094",
    "sourceId": "10X-094",
    "rank": 94,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Portfolio",
    "title": "Create portfolio dependency mapping",
    "detail": "Map the top 15 active/strategic lanes.",
    "mechanism": "Graph projects to services, machines, skills, data, and decisions.",
    "successMetric": "Blocked work automatically identifies the prerequisite and owner.",
    "horizon": "60 days",
    "owner": "jcOS",
    "leverage": 77,
    "tickets": 4
  },
  {
    "id": "10x-095",
    "sourceId": "10X-095",
    "rank": 95,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create shared identity and user-context service",
    "detail": "Move common machine/path data into JAY.",
    "mechanism": "Local profile with devices, capabilities, locations, and preferences.",
    "successMetric": "New tools start with correct defaults without repeated setup questions.",
    "horizon": "90 days",
    "owner": "JAY",
    "leverage": 77,
    "tickets": 4
  },
  {
    "id": "10x-096",
    "sourceId": "10X-096",
    "rank": 96,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Revenue",
    "title": "Convert field jobs into a service product",
    "detail": "Create one service-job template from the completed install.",
    "mechanism": "Standard scope, diagnostic fee, labor bands, materials, warranty, invoice, and referral request.",
    "successMetric": "Next job is quoted and documented using the template.",
    "horizon": "30 days",
    "owner": "Bob + Jay",
    "leverage": 76,
    "tickets": 4
  },
  {
    "id": "10x-097",
    "sourceId": "10X-097",
    "rank": 97,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Shared platform",
    "title": "Create a reusable benchmark/test harness SDK",
    "detail": "Apply to JTT, Track Ripper, and DJ Cleaner.",
    "mechanism": "Common smoke, integration, install, rollback, performance, and evidence reporting.",
    "successMetric": "A new product adopts the test harness in under four hours.",
    "horizon": "90 days",
    "owner": "Neo",
    "leverage": 75,
    "tickets": 3
  },
  {
    "id": "10x-098",
    "sourceId": "10X-098",
    "rank": 98,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Product-specific",
    "title": "Create one polished Fight Like Men vertical slice",
    "detail": "Freeze other content and commission/generate final-quality assets for this slice.",
    "mechanism": "One hero character, one rival, one arena, one complete combat/report loop.",
    "successMetric": "Ten playtesters understand the hook and want another match.",
    "horizon": "90 days",
    "owner": "FightLikeMen",
    "leverage": 75,
    "tickets": 3
  },
  {
    "id": "10x-099",
    "sourceId": "10X-099",
    "rank": 99,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Product-specific",
    "title": "Reduce EDC Pro to an engineerable MVP",
    "detail": "Create dimensioned foam/3D-printed ergonomic prototype.",
    "mechanism": "Prioritize grip, blade, bit driver, pen, and modular storage; defer battery/light/magnet.",
    "successMetric": "Ten users can safely perform core tasks and prefer it to separate tools.",
    "horizon": "90 days",
    "owner": "Štuff",
    "leverage": 72,
    "tickets": 3
  },
  {
    "id": "10x-100",
    "sourceId": "10X-100",
    "rank": 100,
    "tier": "Tier 4 - Sequence / preserve",
    "category": "Product-specific",
    "title": "Benchmark That One Photo on real memories",
    "detail": "Build benchmark and run baseline.",
    "mechanism": "Curate 500 photos/videos with 100 natural-language questions and expected answers.",
    "successMetric": "Top-5 retrieval precision >=85% on the benchmark.",
    "horizon": "90 days",
    "owner": "Photo platform",
    "leverage": 70,
    "tickets": 3
  }
] as Omit<TenXMission, 'status'>[];

export const TEN_X_MISSIONS: TenXMission[] = RAW_TEN_X_MISSIONS.map((mission) => ({
  ...mission,
  status: 'ready',
}));

